/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.empleados;

import backend.Tienda;
import conexion_DB.Empleado_DB;
import conexion_DB.Tienda_DB;
import frontend.Principal_E;
import javax.swing.JOptionPane;

/**
 *
 * @author lguilln
 */
public class Registrar_Tienda extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registrar_Producto
     */
    public Registrar_Tienda() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblCodigoFabricante = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblGarantia = new javax.swing.JLabel();
        lblPrecio1 = new javax.swing.JLabel();
        lblCodigoFabricante1 = new javax.swing.JLabel();
        tiendaNombre = new javax.swing.JTextField();
        tiendaCodigo = new javax.swing.JTextField();
        tiendaTelefono2 = new javax.swing.JTextField();
        tiendaCorreo = new javax.swing.JTextField();
        tiendaDireccion = new javax.swing.JTextField();
        tiendaTelefono1 = new javax.swing.JTextField();
        tiendaHorario = new javax.swing.JTextField();
        registrarProducto = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar Tienda");

        lblNombre.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblNombre.setText("Nombre:");

        lblCodigoFabricante.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblCodigoFabricante.setText("Direccion: ");

        lblCodigo.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblCodigo.setText("Código:");

        lblPrecio.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblPrecio.setText("Telefono 1:   ");

        lblGarantia.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblGarantia.setText("Telefono 2:");

        lblPrecio1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblPrecio1.setText("Horario:");

        lblCodigoFabricante1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblCodigoFabricante1.setText("Correo:");

        tiendaNombre.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tiendaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiendaNombreActionPerformed(evt);
            }
        });
        tiendaNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiendaNombreKeyTyped(evt);
            }
        });

        tiendaCodigo.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tiendaCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiendaCodigoKeyTyped(evt);
            }
        });

        tiendaTelefono2.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tiendaTelefono2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiendaTelefono2KeyTyped(evt);
            }
        });

        tiendaCorreo.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tiendaCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiendaCorreoKeyTyped(evt);
            }
        });

        tiendaDireccion.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tiendaDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiendaDireccionKeyTyped(evt);
            }
        });

        tiendaTelefono1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tiendaTelefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiendaTelefono1KeyTyped(evt);
            }
        });

        tiendaHorario.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tiendaHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiendaHorarioActionPerformed(evt);
            }
        });
        tiendaHorario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiendaHorarioKeyTyped(evt);
            }
        });

        registrarProducto.setBackground(new java.awt.Color(102, 255, 0));
        registrarProducto.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        registrarProducto.setText("Registrar");
        registrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registrarProducto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigoFabricante1)
                            .addComponent(lblNombre))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tiendaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tiendaDireccion)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(tiendaCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGarantia)
                            .addComponent(lblPrecio)
                            .addComponent(lblCodigo)
                            .addComponent(lblPrecio1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tiendaCodigo)
                            .addComponent(tiendaTelefono1)
                            .addComponent(tiendaTelefono2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tiendaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigo)
                            .addComponent(tiendaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio)
                            .addComponent(tiendaTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGarantia)
                            .addComponent(tiendaTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio1)
                            .addComponent(tiendaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombre)
                            .addComponent(tiendaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigoFabricante)
                            .addComponent(tiendaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigoFabricante1)
                            .addComponent(tiendaCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(registrarProducto)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiendaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiendaNombreActionPerformed

    }//GEN-LAST:event_tiendaNombreActionPerformed

    private void tiendaNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiendaNombreKeyTyped
        char caracter = evt.getKeyChar();

        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter < ' ' || caracter > ' ') && (caracter < '0' || caracter > '9')) {
            evt.consume();
        }
        if (tiendaNombre.getText().length() == 45) {
            evt.consume();
        }
    }//GEN-LAST:event_tiendaNombreKeyTyped

    private void tiendaCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiendaCodigoKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < 'A' || caracter > 'Z') && (caracter < '0' || caracter > '9') && (caracter != '-' || tiendaCorreo.getText().contains("-")) ) {
            evt.consume();
        }
        if (tiendaCodigo.getText().length() == 10) {
            evt.consume();
        }

    }//GEN-LAST:event_tiendaCodigoKeyTyped

    private void tiendaTelefono2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiendaTelefono2KeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }
        if (tiendaTelefono2.getText().length() == 8) {
            evt.consume();
        }
    }//GEN-LAST:event_tiendaTelefono2KeyTyped

    private void tiendaCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiendaCorreoKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter < '0' || caracter > '9') && (caracter != '-') && (caracter != '_') 
                && (caracter != '.') && (caracter != '@' || tiendaCorreo.getText().contains("@")) ) {
            evt.consume();
        }
        if (tiendaCorreo.getText().length() == 45) {
            evt.consume();
        }
    }//GEN-LAST:event_tiendaCorreoKeyTyped

    private void tiendaDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiendaDireccionKeyTyped
        if (tiendaDireccion.getText().length() == 40) {
            evt.consume();
        }
    }//GEN-LAST:event_tiendaDireccionKeyTyped

    private void tiendaTelefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiendaTelefono1KeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }
        if (tiendaTelefono2.getText().length() == 8) {
            evt.consume();
        }
    }//GEN-LAST:event_tiendaTelefono1KeyTyped

    private void tiendaHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiendaHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiendaHorarioActionPerformed

    private void tiendaHorarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiendaHorarioKeyTyped
            if (tiendaHorario.getText().length() == 45) {
            evt.consume();
                    }
    }//GEN-LAST:event_tiendaHorarioKeyTyped

    private void registrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProductoActionPerformed

        String nombre = tiendaNombre.getText();
        String codigo = tiendaCodigo.getText();
        String telefono1 = tiendaTelefono1.getText();
        String telefono2 = tiendaTelefono2.getText();
        String horario = tiendaHorario.getText();
        String correo = tiendaCorreo.getText();
        String direccion = tiendaDireccion.getText();

        if(tiendaNombre.equals("") ||tiendaCodigo.equals("") || tiendaTelefono1.equals("") || tiendaDireccion.equals("")){
            JOptionPane.showMessageDialog(null, "Faltan Campos Obligatorios");
        }else{
            Tienda  ingresar = new Tienda(nombre, codigo, telefono1, telefono2, horario, correo, direccion);
            conexion_DB.Tienda_DB agregar = new Tienda_DB();
            if(!agregar.insertarTienda(ingresar))
            {
                JOptionPane.showMessageDialog(null, "Ingreso Incorrrecto" + nombre + "Dato no Valido" + codigo +"Dato no Valido" + telefono1 + "Dato no Valido"
                    + telefono2 +  "Dato no Valido" + horario + "Dato no Valido" + correo + "Dato no Valido" + direccion + "Dato no Valido");
            }else{
                JOptionPane.showMessageDialog(null, "Ingresó nuevo Tienda");
                Principal_E regresar = new Principal_E();
                regresar.setVisible(true);
                this.setVisible(false);
            }
        }

    }//GEN-LAST:event_registrarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoFabricante;
    private javax.swing.JLabel lblCodigoFabricante1;
    private javax.swing.JLabel lblGarantia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JButton registrarProducto;
    private javax.swing.JTextField tiendaCodigo;
    private javax.swing.JTextField tiendaCorreo;
    private javax.swing.JTextField tiendaDireccion;
    private javax.swing.JTextField tiendaHorario;
    private javax.swing.JTextField tiendaNombre;
    private javax.swing.JTextField tiendaTelefono1;
    private javax.swing.JTextField tiendaTelefono2;
    // End of variables declaration//GEN-END:variables
}
