/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.empleados;

import backend.Tiempo;
import conexion_DB.Tiempo_DB;
import frontend.Principal_E;
import javax.swing.JOptionPane;

/**
 *
 * @author lguilln
 */
public class Registrar_Tiempo_Tienda extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registrar_Producto
     */
    public Registrar_Tiempo_Tienda() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblPrecio1 = new javax.swing.JLabel();
        tiendaCodigo2 = new javax.swing.JTextField();
        tiendaCodigo1 = new javax.swing.JTextField();
        tiendaTiempo = new javax.swing.JTextField();
        registrarProducto = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar Tiempo en Tienda");

        lblNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblNombre.setText("Código Tienda 1:");

        lblNombre1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblNombre1.setText("Código Tienda 2:");

        lblPrecio1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblPrecio1.setText("Tiempo (Dias)");

        tiendaCodigo2.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tiendaCodigo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiendaCodigo2KeyTyped(evt);
            }
        });

        tiendaCodigo1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tiendaCodigo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiendaCodigo1KeyTyped(evt);
            }
        });

        tiendaTiempo.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tiendaTiempo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiendaTiempoKeyTyped(evt);
            }
        });

        registrarProducto.setBackground(new java.awt.Color(102, 255, 0));
        registrarProducto.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        registrarProducto.setText("Registrar");
        registrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrarProducto)
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre1)
                    .addComponent(lblPrecio1)
                    .addComponent(lblNombre))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tiendaCodigo1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(tiendaCodigo2)
                    .addComponent(tiendaTiempo))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(tiendaCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1)
                    .addComponent(tiendaCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPrecio1)
                    .addComponent(tiendaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(registrarProducto)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiendaCodigo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiendaCodigo2KeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < 'A' || caracter > 'Z') && (caracter < '0' || caracter > '9') && (caracter != '-' || tiendaCodigo2.getText().contains("-"))) {
            evt.consume();
        }
        if (tiendaCodigo2.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_tiendaCodigo2KeyTyped

    private void tiendaCodigo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiendaCodigo1KeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < 'A' || caracter > 'Z') && (caracter < '0' || caracter > '9') && (caracter != '-' || tiendaCodigo1.getText().contains("-"))) {
            evt.consume();
        }
        if (tiendaCodigo1.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_tiendaCodigo1KeyTyped

    private void tiendaTiempoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiendaTiempoKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }
        if (tiendaTiempo.getText().length() == 8) {
            evt.consume();
        }
    }//GEN-LAST:event_tiendaTiempoKeyTyped

    private void registrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProductoActionPerformed
        String tienda1 = tiendaCodigo1.getText();
        String tienda2 = tiendaCodigo2.getText();
        int tiempo = 0;

        if (!tiendaTiempo.getText().equals("")) {
            tiempo = Integer.parseInt(tiendaTiempo.getText());
        }
        if (tienda1.equals("") || tienda2.equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese CAMPOS OBLIGATORIOS");
        } else {
            Tiempo ingresar = new Tiempo(tienda1, tienda2, tiempo);
            conexion_DB.Tiempo_DB agregar = new Tiempo_DB();
            if (!agregar.insertarTiempo(ingresar)) {
                JOptionPane.showMessageDialog(null, "Ingreso Incorrrecto");
            } else {
                JOptionPane.showMessageDialog(null, "Ingresó nuevo Tienda");
                Principal_E regresar = new Principal_E();
                regresar.setVisible(true);
                this.setVisible(false);
            }
        }

    }//GEN-LAST:event_registrarProductoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JButton registrarProducto;
    private javax.swing.JTextField tiendaCodigo1;
    private javax.swing.JTextField tiendaCodigo2;
    private javax.swing.JTextField tiendaTiempo;
    // End of variables declaration//GEN-END:variables
}
