/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.empleados;

import backend.Cliente;
import conexion_DB.Cliente_DB;
import frontend.Principal_E;
import javax.swing.JOptionPane;

/**
 *
 * @author lguilln
 */
public class Registrar_Cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registrar_Producto
     */
    public Registrar_Cliente() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        clienteNombre = new javax.swing.JTextField();
        lblCodigoFabricante = new javax.swing.JLabel();
        clienteDPI = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        clienteCredito = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        clienteNIT = new javax.swing.JTextField();
        lblGarantia = new javax.swing.JLabel();
        clienteTelefono = new javax.swing.JTextField();
        clienteDireccion = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        registrar1 = new javax.swing.JButton();
        registrarProducto = new javax.swing.JButton();
        clienteCorreo = new javax.swing.JTextField();
        lblGarantia1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar Clientes");

        lblNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblNombre.setText("Nombre:");

        clienteNombre.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        clienteNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteNombreActionPerformed(evt);
            }
        });
        clienteNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clienteNombreKeyTyped(evt);
            }
        });

        lblCodigoFabricante.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCodigoFabricante.setText("CUI:");

        clienteDPI.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        clienteDPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteDPIActionPerformed(evt);
            }
        });
        clienteDPI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clienteDPIKeyTyped(evt);
            }
        });

        lblCodigo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCodigo.setText("Credito Compra:");

        clienteCredito.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        clienteCredito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clienteCreditoKeyTyped(evt);
            }
        });

        lblPrecio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblPrecio.setText("Nit:");

        clienteNIT.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        clienteNIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clienteNITKeyTyped(evt);
            }
        });

        lblGarantia.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblGarantia.setText("Telefono:");

        clienteTelefono.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        clienteTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clienteTelefonoKeyTyped(evt);
            }
        });

        clienteDireccion.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        clienteDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clienteDireccionKeyTyped(evt);
            }
        });

        lblDescripcion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblDescripcion.setText("Direccion:");

        registrar.setBackground(new java.awt.Color(102, 255, 0));
        registrar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        registrar1.setBackground(new java.awt.Color(102, 255, 0));
        registrar1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        registrar1.setText("Atras");
        registrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar1ActionPerformed(evt);
            }
        });

        registrarProducto.setBackground(new java.awt.Color(102, 255, 0));
        registrarProducto.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        registrarProducto.setText("Registrar");
        registrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProductoActionPerformed(evt);
            }
        });

        clienteCorreo.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        clienteCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clienteCorreoKeyTyped(evt);
            }
        });

        lblGarantia1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblGarantia1.setText("Correo Electronico:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(registrar)
                .addGap(284, 284, 284)
                .addComponent(registrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309)
                .addComponent(registrarProducto)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGarantia1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clienteCorreo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigoFabricante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clienteDPI))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clienteCredito))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGarantia)
                                .addGap(27, 27, 27)
                                .addComponent(clienteTelefono))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrecio)
                                .addGap(18, 18, 18)
                                .addComponent(clienteNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescripcion)
                        .addGap(18, 18, 18)
                        .addComponent(clienteDireccion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigo)
                        .addComponent(clienteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoFabricante)
                    .addComponent(clienteDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio)
                    .addComponent(clienteNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGarantia)
                    .addComponent(clienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGarantia1)
                    .addComponent(clienteCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar)
                    .addComponent(registrar1)
                    .addComponent(registrarProducto))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteDPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteDPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteDPIActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarActionPerformed

    private void registrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrar1ActionPerformed

    private void registrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProductoActionPerformed

        String nombre = clienteNombre.getText();
        String nit = clienteNIT.getText();
        String telefono = clienteTelefono.getText();
        Double creditoCompra = 0.0;
        if (!clienteCredito.getText().equals("")) {
            creditoCompra = Double.parseDouble(clienteCredito.getText());
        }
        String dpi = clienteDPI.getText();
        String correo = clienteCorreo.getText();
        String direccion = clienteDireccion.getText();

        if (nombre.equals("") || nit.equals("") || telefono.equals("")) {
            JOptionPane.showMessageDialog(null, "Faltan Campos Obligatorios");
        } else {
            Cliente ingresar = new Cliente(nombre, nit, telefono, creditoCompra, dpi, correo, direccion);
            conexion_DB.Cliente_DB agregar = new Cliente_DB();
            if (!agregar.insertarCliente(ingresar)) {
                JOptionPane.showMessageDialog(null, "Ingreso Incorrrecto" + nombre + "Dato no Valido" + nit + "Dato no Valido"
                        + telefono + "DDato no Valido" + creditoCompra + "Dato no Valido" + dpi + "Dato no Valido" + correo + "Dato no Valido" + direccion + "Dato no Valido");

            } else {
                JOptionPane.showMessageDialog(null, "Ingresó nuevo Cliente");
                Principal_E regresar = new Principal_E();
                regresar.setVisible(true);
                this.setVisible(false);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_registrarProductoActionPerformed

    private void clienteNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteNombreActionPerformed

    }//GEN-LAST:event_clienteNombreActionPerformed

    private void clienteTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clienteTelefonoKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }
        if (clienteTelefono.getText().length() == 8) {
            evt.consume();
        }
    }//GEN-LAST:event_clienteTelefonoKeyTyped

    private void clienteDPIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clienteDPIKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }
        if (clienteDPI.getText().length() == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_clienteDPIKeyTyped

    private void clienteNITKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clienteNITKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter < '0' || caracter > '9') && (caracter != '-' || clienteNIT.getText().contains("-")) ) {
            evt.consume();
        }
        if (clienteNIT.getText().length() == 13) {
            evt.consume();
        }
    }//GEN-LAST:event_clienteNITKeyTyped

    private void clienteNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clienteNombreKeyTyped
        char caracter = evt.getKeyChar();

        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter < ' ' || caracter > ' ') && (caracter < '0' || caracter > '9')) {
            evt.consume();
        }
        if (clienteNombre.getText().length() == 45) {
            evt.consume();
        }
    }//GEN-LAST:event_clienteNombreKeyTyped

    private void clienteDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clienteDireccionKeyTyped
        if (clienteDireccion.getText().length() == 40) {
            evt.consume();
        }

    }//GEN-LAST:event_clienteDireccionKeyTyped

    private void clienteCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clienteCorreoKeyTyped
    char caracter = evt.getKeyChar();
        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter < '0' || caracter > '9') && (caracter != '-') && (caracter != '_') && (caracter != '.') && (caracter != '@' || clienteCorreo.getText().contains("@")) ) {
            evt.consume();
        }
        if (clienteCorreo.getText().length() == 45) {
            evt.consume();
        }
    }//GEN-LAST:event_clienteCorreoKeyTyped

    private void clienteCreditoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clienteCreditoKeyTyped
         char caracter = evt.getKeyChar();
        if ((caracter < '0' || caracter > '9') && (caracter != '.' || clienteCredito.getText().contains("."))) {
            evt.consume();
        }
        
   
    }//GEN-LAST:event_clienteCreditoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clienteCorreo;
    private javax.swing.JTextField clienteCredito;
    private javax.swing.JTextField clienteDPI;
    private javax.swing.JTextField clienteDireccion;
    private javax.swing.JTextField clienteNIT;
    private javax.swing.JTextField clienteNombre;
    private javax.swing.JTextField clienteTelefono;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoFabricante;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblGarantia;
    private javax.swing.JLabel lblGarantia1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JButton registrar;
    private javax.swing.JButton registrar1;
    private javax.swing.JButton registrarProducto;
    // End of variables declaration//GEN-END:variables
}
