/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.empleados;

import backend.Empleado;
import backend.Producto;
import conexion_DB.Empleado_DB;
import conexion_DB.Producto_DB;
import frontend.Principal_E;
import javax.swing.JOptionPane;

/**
 *
 * @author lguilln
 */
public class Registrar_Producto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registrar_Producto
     */
    public Registrar_Producto() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        productoNombre = new javax.swing.JTextField();
        lblCodigoFabricante = new javax.swing.JLabel();
        productoCodigoFabricante = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        productoCodigo = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        productoPrecio = new javax.swing.JTextField();
        lblGarantia = new javax.swing.JLabel();
        productoGarantia = new javax.swing.JTextField();
        productoDescripcion = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        lblCodigoFabricante1 = new javax.swing.JLabel();
        productoTiendaC = new javax.swing.JTextField();
        lblPrecio1 = new javax.swing.JLabel();
        productoTiendaI = new javax.swing.JTextField();
        inentario = new javax.swing.JLabel();
        productoNombre1 = new javax.swing.JTextField();
        registrarProducto1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar Producto");

        lblNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblNombre.setText("Nombre:");

        productoNombre.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        productoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productoNombreKeyTyped(evt);
            }
        });

        lblCodigoFabricante.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCodigoFabricante.setText("Código Fabricante:");

        productoCodigoFabricante.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        productoCodigoFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoCodigoFabricanteActionPerformed(evt);
            }
        });
        productoCodigoFabricante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productoCodigoFabricanteKeyTyped(evt);
            }
        });

        lblCodigo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCodigo.setText("Código:");

        productoCodigo.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        productoCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productoCodigoKeyTyped(evt);
            }
        });

        lblPrecio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblPrecio.setText("Precio:   ");

        productoPrecio.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        productoPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productoPrecioKeyTyped(evt);
            }
        });

        lblGarantia.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblGarantia.setText("Garantía (M):");

        productoGarantia.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        productoGarantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoGarantiaActionPerformed(evt);
            }
        });
        productoGarantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productoGarantiaKeyTyped(evt);
            }
        });

        productoDescripcion.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        lblDescripcion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblDescripcion.setText("Descripcion:");

        lblCodigoFabricante1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCodigoFabricante1.setText("Código Tienda:");

        productoTiendaC.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        productoTiendaC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productoTiendaCKeyTyped(evt);
            }
        });

        lblPrecio1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblPrecio1.setText("Cantidad a Ingresar:");

        productoTiendaI.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        productoTiendaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoTiendaIActionPerformed(evt);
            }
        });
        productoTiendaI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productoTiendaIKeyTyped(evt);
            }
        });

        inentario.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        inentario.setText("Inventario:");

        productoNombre1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        productoNombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productoNombre1KeyTyped(evt);
            }
        });

        registrarProducto1.setBackground(new java.awt.Color(102, 255, 0));
        registrarProducto1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        registrarProducto1.setText("Registrar");
        registrarProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProducto1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productoTiendaC, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(inentario)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registrarProducto1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNombre)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(productoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCodigoFabricante)
                                        .addComponent(lblCodigoFabricante1)
                                        .addComponent(lblPrecio1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(productoCodigoFabricante)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(64, 64, 64)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblCodigo)
                                            .addGap(18, 18, 18)
                                            .addComponent(productoCodigo))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblPrecio)
                                            .addGap(18, 18, 18)
                                            .addComponent(productoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblGarantia)
                                            .addGap(27, 27, 27)
                                            .addComponent(productoGarantia))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(productoTiendaI, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblDescripcion)
                            .addGap(50, 50, 50)
                            .addComponent(productoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigo)
                        .addComponent(productoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoFabricante)
                    .addComponent(productoCodigoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio)
                    .addComponent(productoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGarantia)
                    .addComponent(productoGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoFabricante1)
                    .addComponent(productoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio1)
                    .addComponent(productoTiendaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inentario)
                    .addComponent(productoTiendaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDescripcion)
                        .addGap(52, 52, 52)))
                .addGap(40, 40, 40)
                .addComponent(registrarProducto1)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productoCodigoFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoCodigoFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoCodigoFabricanteActionPerformed

    private void productoGarantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoGarantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoGarantiaActionPerformed

    private void productoTiendaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoTiendaIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoTiendaIActionPerformed

    private void productoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productoNombreKeyTyped
        
        // TODO add your handling code here:
    }//GEN-LAST:event_productoNombreKeyTyped

    private void productoCodigoFabricanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productoCodigoFabricanteKeyTyped
         char caracter = evt.getKeyChar();

        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter < ' ' || caracter > ' ') && (caracter < '0' || caracter > '9')) {
            evt.consume();
        }
        if (productoCodigoFabricante.getText().length() == 45) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_productoCodigoFabricanteKeyTyped

    private void productoNombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productoNombre1KeyTyped
                        char caracter = evt.getKeyChar();
        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter < '0' || caracter > '9') && (caracter != '-' || productoNombre1.getText().contains("-"))) {
            evt.consume();
        }
        if (productoNombre1.getText().length() == 13) {
            evt.consume();
        }
    }//GEN-LAST:event_productoNombre1KeyTyped

    private void productoPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productoPrecioKeyTyped
                        char caracter = evt.getKeyChar();
        if ((caracter < '0' || caracter > '9') && (caracter != '.' || productoPrecio.getText().contains("."))) {
            evt.consume();
        }

    }//GEN-LAST:event_productoPrecioKeyTyped

    private void productoGarantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productoGarantiaKeyTyped
                      char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }
        if (productoGarantia.getText().length() == 8) {
            evt.consume();
        }
    
    }//GEN-LAST:event_productoGarantiaKeyTyped

    private void productoTiendaIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productoTiendaIKeyTyped
                      char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }
        if (productoTiendaI.getText().length() == 8) {
            evt.consume();
        }
    }//GEN-LAST:event_productoTiendaIKeyTyped

    private void productoTiendaCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productoTiendaCKeyTyped
                      char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }
        if (productoTiendaC.getText().length() == 8) {
            evt.consume();
        }
    }//GEN-LAST:event_productoTiendaCKeyTyped

    private void productoCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productoCodigoKeyTyped
                                char caracter = evt.getKeyChar();
        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter < '0' || caracter > '9') && (caracter != '-' || productoCodigo.getText().contains("-"))) {
            evt.consume();
        }
        if (productoCodigo.getText().length() == 13) {
            evt.consume();
        }
    }//GEN-LAST:event_productoCodigoKeyTyped

    private void registrarProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProducto1ActionPerformed

       String nombre = productoNombre.getText();
        String fabricante = productoCodigoFabricante.getText();
        String codigo = productoCodigo.getText();
        int cantidad = 0;
        Double precio = 0.0;
        String idTienda = productoNombre1.getText();
        String descripcion = productoDescripcion.getText();
        int garantia = 0;
        if(!productoTiendaC.getText().equals("")){
            cantidad = Integer.parseInt(productoTiendaC.getText());
        }
        if(!productoPrecio.getText().equals("")){
            precio = Double.parseDouble(productoPrecio.getText());
        }
         if(!productoGarantia.getText().equals("")){
            garantia = Integer.parseInt(productoGarantia.getText());
        }
      
        
        if(nombre.equals("") || fabricante.equals("") || codigo.equals("") || idTienda.equals("") ){
            JOptionPane.showMessageDialog(null, "Ingrese CAMPOS OBLIGATORIOS");
        }else{
           Producto  ingresar = new Producto(nombre, fabricante, codigo, cantidad, precio , idTienda, descripcion, garantia);
            conexion_DB.Producto_DB agregar = new Producto_DB();
            if(!agregar.insertarProducto(ingresar))
                {
                        JOptionPane.showMessageDialog(null, "Ingreso Incorrrecto");   
                }else{
                JOptionPane.showMessageDialog(null, "Ingresó nuevo Empleado");
                Principal_E regresar = new Principal_E();
                regresar.setVisible(true);
                this.setVisible(false);
             }
        }
    }//GEN-LAST:event_registrarProducto1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel inentario;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoFabricante;
    private javax.swing.JLabel lblCodigoFabricante1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblGarantia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JTextField productoCodigo;
    private javax.swing.JTextField productoCodigoFabricante;
    private javax.swing.JTextField productoDescripcion;
    private javax.swing.JTextField productoGarantia;
    private javax.swing.JTextField productoNombre;
    private javax.swing.JTextField productoNombre1;
    private javax.swing.JTextField productoPrecio;
    private javax.swing.JTextField productoTiendaC;
    private javax.swing.JTextField productoTiendaI;
    private javax.swing.JButton registrarProducto1;
    // End of variables declaration//GEN-END:variables
}
