/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.empleados;

import backend.Empleado;
import conexion_DB.Empleado_DB;
import frontend.Principal_E;
import javax.swing.JOptionPane;

/**
 *
 * @author lguilln
 */
public class Registrar_Empleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registrar_Producto
     */
    public Registrar_Empleado() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrecio = new javax.swing.JLabel();
        empleadoNIT = new javax.swing.JTextField();
        lblGarantia = new javax.swing.JLabel();
        empleadoTelefono = new javax.swing.JTextField();
        empleadoDireccion = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        empleadoNombre = new javax.swing.JTextField();
        lblCodigoFabricante = new javax.swing.JLabel();
        empleadoDPI = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        empleadoCorreo = new javax.swing.JTextField();
        empleadoCodigo = new javax.swing.JTextField();
        lblGarantia1 = new javax.swing.JLabel();
        registrarProducto = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar Empleados");

        lblPrecio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblPrecio.setText("Nit:");

        empleadoNIT.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        empleadoNIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                empleadoNITKeyTyped(evt);
            }
        });

        lblGarantia.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblGarantia.setText("Telefono:");

        empleadoTelefono.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        empleadoTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                empleadoTelefonoKeyTyped(evt);
            }
        });

        empleadoDireccion.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        empleadoDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                empleadoDireccionKeyTyped(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblNombre.setText("Nombre:");

        lblDescripcion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblDescripcion.setText("Direccion:");

        empleadoNombre.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        empleadoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoNombreActionPerformed(evt);
            }
        });
        empleadoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                empleadoNombreKeyTyped(evt);
            }
        });

        lblCodigoFabricante.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCodigoFabricante.setText("CUI:");

        empleadoDPI.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        empleadoDPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoDPIActionPerformed(evt);
            }
        });
        empleadoDPI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                empleadoDPIKeyTyped(evt);
            }
        });

        lblCodigo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCodigo.setText("Codigo:");

        empleadoCorreo.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        empleadoCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                empleadoCorreoKeyTyped(evt);
            }
        });

        empleadoCodigo.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        empleadoCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                empleadoCodigoKeyTyped(evt);
            }
        });

        lblGarantia1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblGarantia1.setText("Correo Electronico:");

        registrarProducto.setBackground(new java.awt.Color(102, 255, 0));
        registrarProducto.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        registrarProducto.setText("Registrar");
        registrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrarProducto)
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGarantia1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empleadoCorreo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigoFabricante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(empleadoDPI))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(empleadoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(empleadoCodigo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGarantia)
                                .addGap(27, 27, 27)
                                .addComponent(empleadoTelefono))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrecio)
                                .addGap(18, 18, 18)
                                .addComponent(empleadoNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescripcion)
                        .addGap(18, 18, 18)
                        .addComponent(empleadoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(empleadoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigo)
                        .addComponent(empleadoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoFabricante)
                    .addComponent(empleadoDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio)
                    .addComponent(empleadoNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGarantia)
                    .addComponent(empleadoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGarantia1)
                    .addComponent(empleadoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empleadoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(registrarProducto)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empleadoNITKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empleadoNITKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter < '0' || caracter > '9') 
                && (caracter != '-' || empleadoNIT.getText().contains("-")) ) {
            evt.consume();
        }
        if (empleadoNIT.getText().length() == 13) {
            evt.consume();
        }
    }//GEN-LAST:event_empleadoNITKeyTyped

    private void empleadoTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empleadoTelefonoKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }
        if (empleadoTelefono.getText().length() == 8) {
            evt.consume();
        }
    }//GEN-LAST:event_empleadoTelefonoKeyTyped

    private void empleadoDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empleadoDireccionKeyTyped
        if (empleadoDireccion.getText().length() == 40) {
            evt.consume();
        }
    }//GEN-LAST:event_empleadoDireccionKeyTyped

    private void empleadoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoNombreActionPerformed

    }//GEN-LAST:event_empleadoNombreActionPerformed

    private void empleadoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empleadoNombreKeyTyped
        char caracter = evt.getKeyChar();

        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter < ' ' || caracter > ' ') && (caracter < '0' || caracter > '9')) {
            evt.consume();
        }
        if (empleadoNombre.getText().length() == 45) {
            evt.consume();
        }
    }//GEN-LAST:event_empleadoNombreKeyTyped

    private void empleadoDPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoDPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleadoDPIActionPerformed

    private void empleadoDPIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empleadoDPIKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }
        if (empleadoDPI.getText().length() == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_empleadoDPIKeyTyped

    private void empleadoCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empleadoCorreoKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter < '0' || caracter > '9') && (caracter != '-') 
            && (caracter != '_') && (caracter != '.') && (caracter != '@' || empleadoCorreo.getText().contains("@")) ) {
            evt.consume();
        }
        if (empleadoCorreo.getText().length() == 45) {
            evt.consume();
        }
    }//GEN-LAST:event_empleadoCorreoKeyTyped

    private void registrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProductoActionPerformed

        String nombre = empleadoNombre.getText();
        String codigo = empleadoCodigo.getText();
        String telefono = empleadoTelefono.getText();
        String dpi = empleadoDPI.getText();
        String nit = empleadoNIT.getText();
        String correo = empleadoCorreo.getText();
        String direccion = empleadoDireccion.getText();
        
                if(nombre.equals("") ||codigo.equals("") || telefono.equals("") || dpi.equals("") || correo.equals("") 
                        || empleadoDireccion.equals("")){
            JOptionPane.showMessageDialog(null, "Faltan Campos Obligatorios");
        }else{
            Empleado  ingresar = new Empleado(nombre, codigo, telefono, dpi, nit, correo, direccion);
            conexion_DB.Empleado_DB agregar = new Empleado_DB();
            if(!agregar.insertarEmpleado(ingresar))
                {
                        JOptionPane.showMessageDialog(null, "Ingreso Incorrrecto");   
                }else{
                JOptionPane.showMessageDialog(null, "Ingresó nuevo Empleado");
                Principal_E regresar = new Principal_E();
                regresar.setVisible(true);
                this.setVisible(false);
            }
        }
       
    }//GEN-LAST:event_registrarProductoActionPerformed

    private void empleadoCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empleadoCodigoKeyTyped
                char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }
        if (empleadoCodigo.getText().length() == 10) {
            evt.consume();
        }
        

        
    }//GEN-LAST:event_empleadoCodigoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField empleadoCodigo;
    private javax.swing.JTextField empleadoCorreo;
    private javax.swing.JTextField empleadoDPI;
    private javax.swing.JTextField empleadoDireccion;
    private javax.swing.JTextField empleadoNIT;
    private javax.swing.JTextField empleadoNombre;
    private javax.swing.JTextField empleadoTelefono;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoFabricante;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblGarantia;
    private javax.swing.JLabel lblGarantia1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JButton registrarProducto;
    // End of variables declaration//GEN-END:variables
}
