/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.empleados;

import conexion_DB.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lguilln
 */
public class Ver_Producto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registrar_Producto
     */
    public Ver_Producto() {
        initComponents();

    }

    PreparedStatement ps = null;
    ResultSet rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        lblCodigo1 = new javax.swing.JLabel();
        tienda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        buscar = new javax.swing.JButton();
        buscarCliente1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Productos");

        lblNombre.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblNombre.setText("Nombre:");

        nombre.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        lblCodigo.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblCodigo.setText("Código:");

        codigo.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        lblCodigo1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblCodigo1.setText("Tienda:");

        tienda.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        tablaProducto.setBackground(new java.awt.Color(254, 254, 254));
        tablaProducto.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        tablaProducto.setForeground(new java.awt.Color(1, 1, 1));
        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Fabricante", "Código", "Cantidad", "Precion", "Código Tienda", "Descripción", "Garantía"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProducto);

        buscar.setBackground(new java.awt.Color(102, 255, 0));
        buscar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        buscarCliente1.setBackground(new java.awt.Color(102, 255, 0));
        buscarCliente1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        buscarCliente1.setText("All");
        buscarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCliente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCodigo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar)
                .addGap(18, 18, 18)
                .addComponent(buscarCliente1)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombre)
                        .addComponent(lblCodigo)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscar)
                            .addComponent(buscarCliente1)))
                    .addComponent(lblCodigo1))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    public void limpiarCampos() {
        buscar.setText("");
        codigo.setText("");
        tienda.setText("");
    }

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String campo = buscar.getText();
        String campo1 = codigo.getText();
        String campo2 = tienda.getText();
        String where = "";

        //query del where para mostrarlos en mis texfields
        if (!"".equals(campo) || !"".equals(campo1) || !"".equals(campo2)) {
            where = "WHERE Nombre_Producto = '" + campo + "' OR Codigo_Producto ='" + campo1 + "' OR Codigo_Tienda ='" + campo2 + "'";
        }
        try {
            DefaultTableModel model = new DefaultTableModel();
            tablaProducto.setModel(model);
            Conexion con = new Conexion();
            Connection c = con.obtenerConexion();

            String sql = "SELECT * FROM PRODUCTO " + where;
            ps = c.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadC = rsMd.getColumnCount();

            model.addColumn("Nombre");
            model.addColumn("Fabricante");
            model.addColumn("Código");
            model.addColumn("Cantidad");
            model.addColumn("Precio");
            model.addColumn("Código Tienda");
            model.addColumn("Descripción");
            model.addColumn("Garantía");
            while (rs.next()) {
                Object[] filas = new Object[cantidadC];
                for (int i = 0; i < cantidadC; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                model.addRow(filas);
                limpiarCampos();
            }
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void buscarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCliente1ActionPerformed
        try {
            DefaultTableModel model = new DefaultTableModel();
            tablaProducto.setModel(model);
            Conexion con = new Conexion();
            Connection c = con.obtenerConexion();

            String sql = "SELECT * FROM PRODUCTO ";
            ps = c.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadC = rsMd.getColumnCount();

            model.addColumn("Nombre");
            model.addColumn("Fabricante");
            model.addColumn("Código");
            model.addColumn("Cantidad");
            model.addColumn("Precio");
            model.addColumn("Código Tienda");
            model.addColumn("Descripción");
            model.addColumn("Garantía");
            while (rs.next()) {

                Object[] filas = new Object[cantidadC];
                for (int i = 0; i < cantidadC; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                model.addRow(filas);

            }
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_buscarCliente1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton buscarCliente1;
    private javax.swing.JTextField codigo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigo1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTextField tienda;
    // End of variables declaration//GEN-END:variables
}
