/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.empleados;

import conexion_DB.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lguilln
 */
public class Ver_Cliente extends javax.swing.JInternalFrame {

    PreparedStatement ps = null;
      ResultSet rs = null;
    
    /**
     * Creates new form Registrar_Producto
     */
    public Ver_Cliente() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        clienteNombre = new javax.swing.JTextField();
        lblNit = new javax.swing.JLabel();
        nit = new javax.swing.JTextField();
        nombre = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        buscarCliente1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Clientes");

        lblNombre.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblNombre.setText("Nombre:");

        clienteNombre.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        clienteNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteNombreActionPerformed(evt);
            }
        });

        lblNit.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblNit.setText("Nit:");

        nit.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        nombre.setBackground(new java.awt.Color(102, 255, 0));
        nombre.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        nombre.setText("Buscar");
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        tablaClientes.setBackground(new java.awt.Color(254, 254, 254));
        tablaClientes.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        tablaClientes.setForeground(new java.awt.Color(1, 1, 1));
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "NIT", "Teléfono", "Credito", "DPI", "Correo Electrónico", "Dirección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        buscarCliente1.setBackground(new java.awt.Color(102, 255, 0));
        buscarCliente1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        buscarCliente1.setText("All");
        buscarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCliente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(lblNit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nit, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(nombre)
                .addGap(18, 18, 18)
                .addComponent(buscarCliente1)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombre)
                        .addComponent(nombre)
                        .addComponent(buscarCliente1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNit)
                        .addComponent(nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      public void limpiarCampos(){
        nombre.setText("");
        nit.setText("");
    }
    
    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
         String campo = nombre.getText();
        String campo1 = nit.getText();
        String where = "";
        
        if(!"".equals(campo)||!"".equals(campo1)){
            where = "WHERE Nombre_Cliente = '" + campo + "' OR NIT_Cliente ='" + campo1 + "'";
               }
        try {
            DefaultTableModel model = new DefaultTableModel();
            tablaClientes.setModel(model);
            Conexion con = new Conexion();
            Connection c = con.obtenerConexion();
            
            String sql = "SELECT * FROM CLIENTE " + where ;
            ps = c.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadC = rsMd.getColumnCount();
            
            model.addColumn("Nombre");
            model.addColumn("NIT");
            model.addColumn("Teléfono");
            model.addColumn("Crédito");
            model.addColumn("DPI");
            model.addColumn("Correo Eléctronico");
            model.addColumn("Dirección");
            
            while(rs.next()){
                
                Object [] filas = new Object[cantidadC];
                for(int i = 0; i< cantidadC; i++){
                  filas[i] = rs.getObject(i + 1);
            }
                model.addRow(filas);                
                limpiarCampos();
            }
        }catch(SQLException ex) {         
        }
    }//GEN-LAST:event_nombreActionPerformed

    private void clienteNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteNombreActionPerformed

    private void buscarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCliente1ActionPerformed
try {
            DefaultTableModel model = new DefaultTableModel();
            tablaClientes.setModel(model);
            Conexion con = new Conexion();
            Connection c = con.obtenerConexion();
            
            String sql = "SELECT * FROM CLIENTE ";
            ps = c.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadC = rsMd.getColumnCount();
            
            model.addColumn("Nombre");
            model.addColumn("NIT");
            model.addColumn("Teléfono");
            model.addColumn("Crédito");
            model.addColumn("DPI");
            model.addColumn("Correo Eléctronico");
            model.addColumn("Dirección");
            
            while(rs.next()){
                
                Object [] filas = new Object[cantidadC];
                for(int i = 0; i< cantidadC; i++){
                  filas[i] = rs.getObject(i + 1);
            }
                model.addRow(filas);                
               
            }
        }catch(SQLException ex) {         
        }
    }//GEN-LAST:event_buscarCliente1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarCliente1;
    private javax.swing.JTextField clienteNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField nit;
    private javax.swing.JButton nombre;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
}
