/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.empleados;

import conexion_DB.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lguilln
 */
public class Ver_Tiempo_Tienda extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registrar_Producto
     */
    public Ver_Tiempo_Tienda() {
        initComponents();
        
    }

     public void limpiarCampos(){
        tienda.setText("");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        nombre = new javax.swing.JButton();
        buscarCliente1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTiempo = new javax.swing.JTable();
        tienda = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Tiempo entre Tiendas");
        setPreferredSize(new java.awt.Dimension(1189, 775));

        lblNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblNombre.setText("Código Tienda:");

        nombre.setBackground(new java.awt.Color(102, 255, 0));
        nombre.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        nombre.setText("Buscar");
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        buscarCliente1.setBackground(new java.awt.Color(102, 255, 0));
        buscarCliente1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        buscarCliente1.setText("All");
        buscarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCliente1ActionPerformed(evt);
            }
        });

        tablaTiempo.setBackground(new java.awt.Color(254, 254, 254));
        tablaTiempo.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        tablaTiempo.setForeground(new java.awt.Color(1, 1, 1));
        tablaTiempo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Tienda Origen", "Tienda Destino", "Tiempo En Días"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaTiempo);

        tienda.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblNombre)
                .addGap(30, 30, 30)
                .addComponent(tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nombre)
                .addGap(18, 18, 18)
                .addComponent(buscarCliente1)
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(nombre)
                    .addComponent(buscarCliente1)
                    .addComponent(tienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    PreparedStatement ps = null;
     ResultSet rs = null;
    
    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        String campo = tienda.getText();
        String where = "";
        
        if(!"".equals(campo)){
            where = "WHERE Tienda1 = '" + campo + "' OR Tienda2 = '" + campo + "'" ;
               }
        
        try {
            DefaultTableModel model = new DefaultTableModel();
            tablaTiempo.setModel(model);
            Conexion con = new Conexion();
            Connection c = con.obtenerConexion();
            
            String sql = "SELECT * FROM TIEMPO ";
            ps = c.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadC = rsMd.getColumnCount();
            
            model.addColumn("Codigo");
            model.addColumn("Tienda 1");
            model.addColumn("Tienda 2");
            model.addColumn("Tiempo En Días");
       
            while(rs.next()){
                
                Object [] filas = new Object[cantidadC];
                for(int i = 0; i< cantidadC; i++){
                  filas[i] = rs.getObject(i + 1);
            }
                model.addRow(filas);
                limpiarCampos();
            }
            
        }catch(SQLException ex) {     
        }
    }//GEN-LAST:event_nombreActionPerformed

    private void buscarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCliente1ActionPerformed
              try {
            DefaultTableModel model = new DefaultTableModel();
            tablaTiempo.setModel(model);
            Conexion con = new Conexion();
            Connection c = con.obtenerConexion();
            
            String sql = "SELECT * FROM TIEMPO ";
            ps = c.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadC = rsMd.getColumnCount();
            
            model.addColumn("Codigo");
            model.addColumn("Tienda 1");
            model.addColumn("Tienda 2");
            model.addColumn("Tiempo En Días");
       
            while(rs.next()){
                
                Object [] filas = new Object[cantidadC];
                for(int i = 0; i< cantidadC; i++){
                  filas[i] = rs.getObject(i + 1);
            }
                model.addRow(filas);
                limpiarCampos();
            }
            
        }catch(SQLException ex) {     
        }
    }//GEN-LAST:event_buscarCliente1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarCliente1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JButton nombre;
    private javax.swing.JTable tablaTiempo;
    private javax.swing.JTextField tienda;
    // End of variables declaration//GEN-END:variables
}
