
CREATE SCHEMA IF NOT EXISTS INTELAF;

USE INTELAF;

CREATE TABLE IF NOT EXISTS CLIENTE(
	Nombre_Cliente VARCHAR(45) NOT NULL,
	NIT_Cliente VARCHAR(13) NOT NULL,
	Telefono VARCHAR(10) NOT NULL,
	Credito_Cliente DOUBLE NOT NULL,
	DPI VARCHAR(20) NULL,
	Correo_Electronico VARCHAR(45) NULL,
	Direccion VARCHAR(40) NULL,	

	CONSTRAINT PRIMARY KEY(NIT_Cliente));


CREATE TABLE IF NOT EXISTS EMPLEADO(
	Nombre_Empleado VARCHAR(45) NOT NULL,
	Codigo_Empleado VARCHAR(10) NOT NULL,
	Telefono VARCHAR(10) NOT NULL,
	DPI VARCHAR(20) NOT NULL,
	NIT_Empleado VARCHAR(13) NULL,
	Correo_Electronico VARCHAR (45) NULL,
	Direccion VARCHAR(40) NULL,

	CONSTRAINT PRIMARY KEY(Codigo_Empleado));


CREATE TABLE IF NOT EXISTS TIENDA(
	Nombre_Tienda VARCHAR(45) NOT NULL,
	Direccion VARCHAR(40) NOT NULL,
	Codigo_Tienda VARCHAR(10) NOT NULL,
	Telefono_1 VARCHAR(10) NOT NULL,
	Telefono_2 VARCHAR(10) NULL,
	Correo_Electronico VARCHAR(45) NULL,
	Horario VARCHAR(45) NULL,
	
	CONSTRAINT PRIMARY KEY(Codigo_Tienda));


CREATE TABLE IF NOT EXISTS PRODUCTO(
	Nombre_Producto VARCHAR(45) NOT NULL,
	Fabricante VARCHAR(45) NOT NULL,
	Codigo_Producto VARCHAR(10) NOT NULL,
	Cantidad_Producto INT NOT NULL,
	Precio_Producto DOUBLE NOT NULL,
	Codigo_Tienda VARCHAR(10) NOT NULL,
	Descripcion VARCHAR(200) NULL,
	Garantia INT NULL,
	
	CONSTRAINT PRIMARY KEY(Codigo_Producto, Codigo_Tienda),
	CONSTRAINT FOREIGN KEY(Codigo_Tienda) REFERENCES TIENDA(Codigo_Tienda));


CREATE TABLE IF NOT EXISTS TIEMPO(
	Codigo_Tiempo INT NOT NULL AUTO_INCREMENT,
	Tienda1 VARCHAR(10) NOT NULL,
	Tienda2 VARCHAR(10) NOT NULL,
	Tiempo_Dias INT NOT NULL,

	CONSTRAINT PRIMARY KEY(Codigo_Tiempo),
	CONSTRAINT FOREIGN KEY(Tienda1) REFERENCES TIENDA(Codigo_Tienda),
	CONSTRAINT FOREIGN KEY(Tienda2) REFERENCES TIENDA(Codigo_Tienda));


CREATE TABLE IF NOT EXISTS PEDIDO(
	Codigo_Pedido INT NOT NULL AUTO_INCREMENT,
	Tienda1 VARCHAR(10) NOT NULL,
	Tienda2 VARCHAR(10) NOT NULL,
	Fecha1 DATE NOT NULL,
	NIT_Cliente VARCHAR(13) NOT NULL,
	Total DOUBLE NOT NULL,
	Anticipo_Total DOUBLE NOT NULL,
	Total_Restante DOUBLE  NULL,
	Fecha2 DATE NULL,
	En_Curso VARCHAR(5) NULL,


	CONSTRAINT PRIMARY KEY(Codigo_Pedido), 
	CONSTRAINT FOREIGN KEY(Tienda1) REFERENCES TIENDA(Codigo_Tienda),
	CONSTRAINT FOREIGN KEY(Tienda2) REFERENCES TIENDA(Codigo_Tienda),
	CONSTRAINT FOREIGN KEY(NIT_Cliente) REFERENCES CLIENTE(NIT_Cliente));


CREATE TABLE IF NOT EXISTS GENERAR_PEDIDO(
	Codigo_GeneracionP INT NOT NULL AUTO_INCREMENT,
	Codigo_Pedido INT NOT NULL,
	Fecha1 DATE NOT NULL,
	Codigo_Producto VARCHAR(10) NOT NULL,
	Cantidad INT NOT NULL,
	Total_P DOUBLE NOT NULL,
	Anticipo_Total DOUBLE NOT NULL,
	En_Curso VARCHAR(5) NULL,

	CONSTRAINT PRIMARY KEY(Codigo_GeneracionP, Codigo_Pedido),
	CONSTRAINT FOREIGN KEY(Codigo_Producto) REFERENCES PRODUCTO(Codigo_Producto));
  

CREATE TABLE IF NOT EXISTS VENTA(
	Codigo_Venta INT NOT NULL AUTO_INCREMENT,
	Codigo_Tienda VARCHAR(10) NOT NULL, 
	NIT_Cliente VARCHAR(13) NOT NULL,
	Fecha DATE NOT NULL,
	Codigo_Pedido INT NULL,
	Anticipo_Total DOUBLE NULL,
	Total DOUBLE NOT NULL,
	Total_Restante DOUBLE NOT NULL,

	CONSTRAINT PRIMARY KEY(Codigo_Venta),
	CONSTRAINT FOREIGN KEY(NIT_Cliente) REFERENCES CLIENTE(NIT_Cliente),
	CONSTRAINT FOREIGN KEY(Codigo_Tienda) REFERENCES TIENDA(Codigo_Tienda),
	CONSTRAINT FOREIGN KEY(Codigo_Pedido) REFERENCES PEDIDO(Codigo_Pedido)); 


CREATE TABLE IF NOT EXISTS GENERAR_VENTA(
	Codigo_GeneracionV INT NOT NULL AUTO_INCREMENT, 
	Codigo_Venta INT NOT NULL,
	Codigo_Producto VARCHAR(10) NOT NULL,
	Cantidad INT NOT NULL,
	Cantidad_Producto INT NOT NULL,
	Fecha DATE NOT NULL,
	Codigo_Tienda VARCHAR(10) NOT NULL,
	
	CONSTRAINT PRIMARY KEY(Codigo_GeneracionV),
	CONSTRAINT FOREIGN KEY(Codigo_Venta) REFERENCES VENTA(Codigo_Venta),
	CONSTRAINT FOREIGN KEY(Codigo_Producto) REFERENCES PRODUCTO(Codigo_Producto),
	CONSTRAINT FOREIGN KEY(Codigo_Tienda) REFERENCES TIENDA(Codigo_Tienda));
