/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import frontend.empleados.Editar_Cliente;
import frontend.empleados.Editar_Empleado;
import frontend.empleados.Modificar_Producto_Tienda;
import frontend.empleados.Modificar_Tiempo_Tienda;
import frontend.empleados.Registrar_Cliente;
import frontend.empleados.Registrar_Empleado;
import frontend.empleados.Registrar_Producto;
import frontend.empleados.Registrar_Producto_Tienda;
import frontend.empleados.Registrar_Tiempo_Tienda;
import frontend.empleados.Registrar_Tienda;
import frontend.empleados.Ver_Cliente;
import frontend.empleados.Ver_Empleado;
import frontend.empleados.Ver_Producto;
import frontend.empleados.Ver_Tiempo_Tienda;
import frontend.empleados.Ver_Tienda;
import frontend.reportes.Reporte_Atrasados;
import frontend.reportes.Reporte_Compras;
import frontend.reportes.Reporte_Existencia_Entrada;
import frontend.reportes.Reporte_Mas_Vendido_Tienda;
import frontend.reportes.Reporte_Mas_Vendido;
import frontend.reportes.Reporte_No_Vendido;
import frontend.reportes.Reporte_Pedidos;
import frontend.reportes.Reporte_Pedidos_En_Curso;
import frontend.reportes.Reporte_Pedidos_Entregar;
import java.awt.Color;



/**
 *
 * @author lguilln
 */
public class Principal_E extends javax.swing.JFrame {
    
  
    

    /**
     * Creates new form Inicio
     */
    public Principal_E() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.CYAN);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JPanel();
        menuTrabajadores = new javax.swing.JMenuBar();
        ingresoNuevo = new javax.swing.JMenu();
        registroTienda = new javax.swing.JMenuItem();
        registroEmpleado = new javax.swing.JMenuItem();
        registroCliente = new javax.swing.JMenuItem();
        registroProducto = new javax.swing.JMenuItem();
        registroInventarioProducto = new javax.swing.JMenuItem();
        registroTiempoTiendas = new javax.swing.JMenuItem();
        editarRegistro = new javax.swing.JMenu();
        editarTiempoTienda = new javax.swing.JMenuItem();
        editarInventarioProducto = new javax.swing.JMenuItem();
        editarEmpleado = new javax.swing.JMenuItem();
        editarCLiente = new javax.swing.JMenuItem();
        verRegistro = new javax.swing.JMenu();
        verTienda = new javax.swing.JMenuItem();
        verProducto = new javax.swing.JMenuItem();
        verEmpleado = new javax.swing.JMenuItem();
        verCliente = new javax.swing.JMenuItem();
        verTiempoTienda = new javax.swing.JMenuItem();
        generarVenta = new javax.swing.JMenu();
        realizarVenta = new javax.swing.JMenuItem();
        realizarPedido = new javax.swing.JMenuItem();
        exportarReportes = new javax.swing.JMenu();
        reportePedidoPorLlegarTienda = new javax.swing.JMenuItem();
        reportePedidoLlegoTienda = new javax.swing.JMenuItem();
        reportePedidoAtrasado = new javax.swing.JMenuItem();
        reportePedidoRuta = new javax.swing.JMenuItem();
        reporteComprasCliente = new javax.swing.JMenuItem();
        reportePedidoCliente = new javax.swing.JMenuItem();
        reporteProductoPopular = new javax.swing.JMenuItem();
        reportePedidoModaTienda = new javax.swing.JMenuItem();
        reporteNoVendido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empleado");
        setBackground(new java.awt.Color(0, 255, 51));
        setForeground(new java.awt.Color(102, 255, 51));

        escritorio.setBackground(java.awt.Color.cyan);
        escritorio.setForeground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1253, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
        );

        menuTrabajadores.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

        ingresoNuevo.setText("Ingreso Nuevo");
        ingresoNuevo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        registroTienda.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        registroTienda.setText("Registrar Tienda");
        registroTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroTiendaActionPerformed(evt);
            }
        });
        ingresoNuevo.add(registroTienda);

        registroEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        registroEmpleado.setText("Registrar Empleado");
        registroEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroEmpleadoActionPerformed(evt);
            }
        });
        ingresoNuevo.add(registroEmpleado);

        registroCliente.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        registroCliente.setText("Registrar Cliente");
        registroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroClienteActionPerformed(evt);
            }
        });
        ingresoNuevo.add(registroCliente);

        registroProducto.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        registroProducto.setText("Registrar Producto");
        registroProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroProductoActionPerformed(evt);
            }
        });
        ingresoNuevo.add(registroProducto);

        registroInventarioProducto.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        registroInventarioProducto.setText("Registrar Inventario Tienda");
        registroInventarioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroInventarioProductoActionPerformed(evt);
            }
        });
        ingresoNuevo.add(registroInventarioProducto);

        registroTiempoTiendas.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        registroTiempoTiendas.setText("Registrar Tiempo de Tienda");
        registroTiempoTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroTiempoTiendasActionPerformed(evt);
            }
        });
        ingresoNuevo.add(registroTiempoTiendas);

        menuTrabajadores.add(ingresoNuevo);

        editarRegistro.setText("Editar");
        editarRegistro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        editarTiempoTienda.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        editarTiempoTienda.setText("Tiempo entre Tiendas");
        editarTiempoTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarTiempoTiendaActionPerformed(evt);
            }
        });
        editarRegistro.add(editarTiempoTienda);

        editarInventarioProducto.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        editarInventarioProducto.setText("Inventario");
        editarInventarioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarInventarioProductoActionPerformed(evt);
            }
        });
        editarRegistro.add(editarInventarioProducto);

        editarEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        editarEmpleado.setText("Empleados");
        editarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEmpleadoActionPerformed(evt);
            }
        });
        editarRegistro.add(editarEmpleado);

        editarCLiente.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        editarCLiente.setText("Clientes");
        editarCLiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCLienteActionPerformed(evt);
            }
        });
        editarRegistro.add(editarCLiente);

        menuTrabajadores.add(editarRegistro);

        verRegistro.setText("Ver");
        verRegistro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        verTienda.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        verTienda.setText("Tiendas");
        verTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTiendaActionPerformed(evt);
            }
        });
        verRegistro.add(verTienda);

        verProducto.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        verProducto.setText("Productos");
        verProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verProductoActionPerformed(evt);
            }
        });
        verRegistro.add(verProducto);

        verEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        verEmpleado.setText("Empleados");
        verEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEmpleadoActionPerformed(evt);
            }
        });
        verRegistro.add(verEmpleado);

        verCliente.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        verCliente.setText("Clientes");
        verCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verClienteActionPerformed(evt);
            }
        });
        verRegistro.add(verCliente);

        verTiempoTienda.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        verTiempoTienda.setText("Tiempo de Tienda");
        verTiempoTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTiempoTiendaActionPerformed(evt);
            }
        });
        verRegistro.add(verTiempoTienda);

        menuTrabajadores.add(verRegistro);

        generarVenta.setText("Venta");
        generarVenta.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        realizarVenta.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        realizarVenta.setText("Nueva");
        realizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarVentaActionPerformed(evt);
            }
        });
        generarVenta.add(realizarVenta);

        realizarPedido.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        realizarPedido.setText("Pedido");
        realizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarPedidoActionPerformed(evt);
            }
        });
        generarVenta.add(realizarPedido);

        menuTrabajadores.add(generarVenta);

        exportarReportes.setText("Reportes");
        exportarReportes.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        reportePedidoPorLlegarTienda.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        reportePedidoPorLlegarTienda.setText("Llegará a la Tienda");
        reportePedidoPorLlegarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportePedidoPorLlegarTiendaActionPerformed(evt);
            }
        });
        exportarReportes.add(reportePedidoPorLlegarTienda);

        reportePedidoLlegoTienda.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        reportePedidoLlegoTienda.setText("Está en  la Tienda");
        reportePedidoLlegoTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportePedidoLlegoTiendaActionPerformed(evt);
            }
        });
        exportarReportes.add(reportePedidoLlegoTienda);

        reportePedidoAtrasado.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        reportePedidoAtrasado.setText("Pedido de Entrega Atrasada");
        reportePedidoAtrasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportePedidoAtrasadoActionPerformed(evt);
            }
        });
        exportarReportes.add(reportePedidoAtrasado);

        reportePedidoRuta.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        reportePedidoRuta.setText("Pedido en Ruta");
        reportePedidoRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportePedidoRutaActionPerformed(evt);
            }
        });
        exportarReportes.add(reportePedidoRuta);

        reporteComprasCliente.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        reporteComprasCliente.setText("Compra por CLiente");
        reporteComprasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteComprasClienteActionPerformed(evt);
            }
        });
        exportarReportes.add(reporteComprasCliente);

        reportePedidoCliente.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        reportePedidoCliente.setText("Pedido por CLiente");
        reportePedidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportePedidoClienteActionPerformed(evt);
            }
        });
        exportarReportes.add(reportePedidoCliente);

        reporteProductoPopular.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        reporteProductoPopular.setText("Lo más Vendido Tiempo");
        reporteProductoPopular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteProductoPopularActionPerformed(evt);
            }
        });
        exportarReportes.add(reporteProductoPopular);

        reportePedidoModaTienda.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        reportePedidoModaTienda.setText("Lo más Vendido Tienda");
        reportePedidoModaTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportePedidoModaTiendaActionPerformed(evt);
            }
        });
        exportarReportes.add(reportePedidoModaTienda);

        reporteNoVendido.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        reporteNoVendido.setText("Jamás Vendido");
        reporteNoVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteNoVendidoActionPerformed(evt);
            }
        });
        exportarReportes.add(reporteNoVendido);

        menuTrabajadores.add(exportarReportes);

        setJMenuBar(menuTrabajadores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroTiendaActionPerformed

      Registrar_Tienda registrarTienda = new Registrar_Tienda();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(registrarTienda);
      registrarTienda.show();
    }//GEN-LAST:event_registroTiendaActionPerformed

    private void registroProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroProductoActionPerformed
      Registrar_Producto registrarProducto = new Registrar_Producto();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(registrarProducto);
      registrarProducto.show();
      
    }//GEN-LAST:event_registroProductoActionPerformed

    private void registroInventarioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroInventarioProductoActionPerformed
      
      Registrar_Producto_Tienda registrarProductoTienda = new Registrar_Producto_Tienda();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(registrarProductoTienda);
      registrarProductoTienda.show();
      
      
    }//GEN-LAST:event_registroInventarioProductoActionPerformed

    private void registroEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroEmpleadoActionPerformed
      Registrar_Empleado registrarEmpleado = new Registrar_Empleado();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(registrarEmpleado);
      registrarEmpleado.show();
    }//GEN-LAST:event_registroEmpleadoActionPerformed

    private void registroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroClienteActionPerformed

      Registrar_Cliente registrarCliente = new Registrar_Cliente();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(registrarCliente);
      registrarCliente.show();
    }//GEN-LAST:event_registroClienteActionPerformed

    private void registroTiempoTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroTiempoTiendasActionPerformed
      Registrar_Tiempo_Tienda registrarTiempoTienda = new Registrar_Tiempo_Tienda();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(registrarTiempoTienda);
      registrarTiempoTienda.show();
    }//GEN-LAST:event_registroTiempoTiendasActionPerformed

    private void verTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTiendaActionPerformed
      Ver_Tienda verTienda1 = new Ver_Tienda();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(verTienda1);
      verTienda1.show();
    }//GEN-LAST:event_verTiendaActionPerformed

    private void verProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verProductoActionPerformed
      Ver_Producto verProducto1 = new Ver_Producto();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(verProducto1);
      verProducto1.show();
    }//GEN-LAST:event_verProductoActionPerformed

    private void verEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEmpleadoActionPerformed
      Ver_Empleado verEmpleado1 = new Ver_Empleado();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(verEmpleado1);
      verEmpleado1.show();
    }//GEN-LAST:event_verEmpleadoActionPerformed

    private void verClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verClienteActionPerformed
      Ver_Cliente verCliente1 = new Ver_Cliente();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(verCliente1);
      verCliente1.show();
    }//GEN-LAST:event_verClienteActionPerformed

    private void verTiempoTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTiempoTiendaActionPerformed
      Ver_Tiempo_Tienda verTiempoTienda1 = new Ver_Tiempo_Tienda();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(verTiempoTienda1);
      verTiempoTienda1.show();
    }//GEN-LAST:event_verTiempoTiendaActionPerformed

    private void editarTiempoTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarTiempoTiendaActionPerformed
      Modificar_Tiempo_Tienda editarTiempoTienda1 = new Modificar_Tiempo_Tienda();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(editarTiempoTienda1);
      editarTiempoTienda1.show();
    }//GEN-LAST:event_editarTiempoTiendaActionPerformed

    private void editarInventarioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarInventarioProductoActionPerformed
      Modificar_Producto_Tienda editarInventario = new Modificar_Producto_Tienda();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(editarInventario);
      editarInventario.show();
      
    }//GEN-LAST:event_editarInventarioProductoActionPerformed

    private void realizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarVentaActionPerformed
        // TODO add your handling code here:
        /*NuevaVenta nuevaVenta = new NuevaVenta();
        //asignando el codigo de tienda para la venta
        nuevaVenta.setCodigoTienda(lblCodigoTienda.getText());
        jdpEscritorio.add(nuevaVenta);
        nuevaVenta.show();*/
    }//GEN-LAST:event_realizarVentaActionPerformed

    private void realizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarPedidoActionPerformed
        // TODO add your handling code here:
        /*NuevoPedido nuevoPedido = new NuevoPedido();
        nuevoPedido.setCodigoTienda(lblCodigoTienda.getText());
        jdpEscritorio.add(nuevoPedido);
        nuevoPedido.show();*/
    }//GEN-LAST:event_realizarPedidoActionPerformed

    private void reportePedidoPorLlegarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportePedidoPorLlegarTiendaActionPerformed
      Reporte_Pedidos_Entregar reporteEntrega = new Reporte_Pedidos_Entregar();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(reporteEntrega);
      reporteEntrega.show();
    }//GEN-LAST:event_reportePedidoPorLlegarTiendaActionPerformed

    private void editarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEmpleadoActionPerformed
      Editar_Empleado editarEmpleado1 = new Editar_Empleado();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(editarEmpleado1);
      editarEmpleado1.show();
    }//GEN-LAST:event_editarEmpleadoActionPerformed

    private void editarCLienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCLienteActionPerformed
      Editar_Cliente editarCliente = new Editar_Cliente();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(editarCliente);
      editarCliente.show();
    }//GEN-LAST:event_editarCLienteActionPerformed

    private void reportePedidoLlegoTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportePedidoLlegoTiendaActionPerformed
      Reporte_Existencia_Entrada reporteExistencia = new Reporte_Existencia_Entrada();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(reporteExistencia);
      reporteExistencia.show();
    }//GEN-LAST:event_reportePedidoLlegoTiendaActionPerformed

    private void reportePedidoAtrasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportePedidoAtrasadoActionPerformed
      Reporte_Atrasados reporteAtrasado = new Reporte_Atrasados();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(reporteAtrasado);
      reporteAtrasado.show();
          }//GEN-LAST:event_reportePedidoAtrasadoActionPerformed

    private void reportePedidoRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportePedidoRutaActionPerformed
      Reporte_Pedidos_En_Curso reporteCurso = new Reporte_Pedidos_En_Curso();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(reporteCurso);
      reporteCurso.show();
    }//GEN-LAST:event_reportePedidoRutaActionPerformed

    private void reporteComprasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteComprasClienteActionPerformed
      Reporte_Compras reporteCompras = new Reporte_Compras();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(reporteCompras);
      reporteCompras.show();
    }//GEN-LAST:event_reporteComprasClienteActionPerformed

    private void reportePedidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportePedidoClienteActionPerformed
      Reporte_Pedidos reportePedido = new Reporte_Pedidos();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(reportePedido);
      reportePedido.show();
    }//GEN-LAST:event_reportePedidoClienteActionPerformed

    private void reporteProductoPopularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteProductoPopularActionPerformed
      Reporte_Mas_Vendido reportePopular = new Reporte_Mas_Vendido();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(reportePopular);
      reportePopular.show();
    }//GEN-LAST:event_reporteProductoPopularActionPerformed

    private void reportePedidoModaTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportePedidoModaTiendaActionPerformed
      Reporte_Mas_Vendido_Tienda reportePopularTienda = new Reporte_Mas_Vendido_Tienda(); 
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(reportePopularTienda);
      reportePopularTienda.show();
    }//GEN-LAST:event_reportePedidoModaTiendaActionPerformed

    private void reporteNoVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteNoVendidoActionPerformed
      Reporte_No_Vendido reporteJamasVendido = new Reporte_No_Vendido(); 
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(reporteJamasVendido);
      reporteJamasVendido.show();
    }//GEN-LAST:event_reporteNoVendidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_E.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_E.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_E.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_E.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_E().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem editarCLiente;
    private javax.swing.JMenuItem editarEmpleado;
    private javax.swing.JMenuItem editarInventarioProducto;
    private javax.swing.JMenu editarRegistro;
    private javax.swing.JMenuItem editarTiempoTienda;
    private javax.swing.JPanel escritorio;
    private javax.swing.JMenu exportarReportes;
    private javax.swing.JMenu generarVenta;
    private javax.swing.JMenu ingresoNuevo;
    private javax.swing.JMenuBar menuTrabajadores;
    private javax.swing.JMenuItem realizarPedido;
    private javax.swing.JMenuItem realizarVenta;
    private javax.swing.JMenuItem registroCliente;
    private javax.swing.JMenuItem registroEmpleado;
    private javax.swing.JMenuItem registroInventarioProducto;
    private javax.swing.JMenuItem registroProducto;
    private javax.swing.JMenuItem registroTiempoTiendas;
    private javax.swing.JMenuItem registroTienda;
    private javax.swing.JMenuItem reporteComprasCliente;
    private javax.swing.JMenuItem reporteNoVendido;
    private javax.swing.JMenuItem reportePedidoAtrasado;
    private javax.swing.JMenuItem reportePedidoCliente;
    private javax.swing.JMenuItem reportePedidoLlegoTienda;
    private javax.swing.JMenuItem reportePedidoModaTienda;
    private javax.swing.JMenuItem reportePedidoPorLlegarTienda;
    private javax.swing.JMenuItem reportePedidoRuta;
    private javax.swing.JMenuItem reporteProductoPopular;
    private javax.swing.JMenuItem verCliente;
    private javax.swing.JMenuItem verEmpleado;
    private javax.swing.JMenuItem verProducto;
    private javax.swing.JMenu verRegistro;
    private javax.swing.JMenuItem verTiempoTienda;
    private javax.swing.JMenuItem verTienda;
    // End of variables declaration//GEN-END:variables
}
